"""
GIG-SAATHI — FastAPI Application Entrypoint
Team TECH TITANS | SIH 2026 | Problem SIH26089

Run with: uvicorn api.main:app --reload --port 8000
API docs: http://localhost:8000/docs  (Swagger UI — auto-generated by FastAPI)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# TODO: Import routers once implemented
# from api.workers import router as workers_router
# from api.bookings import router as bookings_router
# from api.payments import router as payments_router
# from api.auth import router as auth_router
# from api.federation import router as federation_router

app = FastAPI(
    title="GIG-SAATHI API",
    description="Cooperative Gig Services Platform — REST API\nSIH 2026 | Problem SIH26089 | Team TECH TITANS",
    version="0.1.0",
    contact={
        "name": "Team TECH TITANS",
        "email": "sih2026@gigsaathi.in",
    },
)

# CORS — allow React frontend during development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# TODO: Register routers
# app.include_router(auth_router, prefix="/api/auth", tags=["Authentication"])
# app.include_router(workers_router, prefix="/api/workers", tags=["Workers"])
# app.include_router(bookings_router, prefix="/api/bookings", tags=["Bookings"])
# app.include_router(payments_router, prefix="/api/payments", tags=["Payments"])
# app.include_router(federation_router, prefix="/api/federation", tags=["Federation"])


@app.get("/", tags=["Health"])
async def root():
    return {
        "service": "GIG-SAATHI API",
        "version": "0.1.0",
        "status": "running",
        "docs": "/docs",
    }


@app.get("/health", tags=["Health"])
async def health_check():
    """
    Health check endpoint for deployment monitoring.
    TODO: Add PostgreSQL and Redis connectivity checks.
    """
    return {"status": "healthy"}
